### ISSUE TITLE
release current version

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/deog#10]

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@yegor256 I think I need ur permission here

**Comment by yegor256** [comment]
@OlesiaSub try again

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.1`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.2`

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.2`

**Comment by OlesiaSub** [comment]
@yegor256 can you please help?

ERROR: Permission to objectionary/deog.git denied to rultor.
fatal: Could not read from remote repository.

**Comment by OlesiaSub** [comment]
@yegor256 can you please help? 
ERROR: Permission to objectionary/deog.git denied to rultor. fatal: Could not read from remote repository.

**Comment by yegor256** [comment]
@OlesiaSub I added permissions to Rultor and removed yours. Please, use Rultor for merging and releasing from now on.

**Comment by OlesiaSub** [comment]
@yegor256 now I can't push to this repo because you removed my permissions...

**Comment by yegor256** [comment]
@OlesiaSub make pull requests and use Rultor to merge them

**Comment by OlesiaSub** [comment]
@yegor256 oh ok I see

**Comment by OlesiaSub** [comment]
@yegor256 wait no I don't. I can't push to any branches.
```
remote: Permission to objectionary/deog.git denied to OlesiaSub.
fatal: unable to access 'https://github.com/objectionary/deog/': The requested URL returned error: 403

```

**Comment by yegor256** [comment]
@OlesiaSub you should use forks, like with all other repositories in `@objectionary`

**Comment by OlesiaSub** [comment]
@yegor256 ok

**Comment by OlesiaSub** [comment]
@rultor release, tag is `0.0.3`
